runtime: custom
env: flex

liveness_check:
  path: /healthz
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  check_interval_sec: 30

readiness_check:
  path: /healthz
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  check_interval_sec: 60
  app_start_timeout_sec: 300

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
